### PR TITLE
Exchange 2013 SP1 CU21 support

### PR DESCRIPTION
**Pull request by davidenco**
Changes included in this PR:
- Exchange 2013 SP1 CU21 support

### CODE REVIEW

**Comment by mettix** [comment]
How do I install this?

**Comment by wish01** [comment]
A month has passed no changes.

**Comment by davidenco** [comment]
FYI, the current version works fine with CU21.

**Comment by MoHegazy** [comment]
> I've been using the current 3.1.0 release for months without any issues with CU21. Give it a go. Other than that, no idea, this project isn't maintained anymore so it's unlikely.

then why when i try to install it give me error version isn`t supported

**Comment by davidenco** [comment]
> 
> 
> > I've been using the current 3.1.0 release for months without any issues with CU21. Give it a go. Other than that, no idea, this project isn't maintained anymore so it's unlikely.
> 
> then why when i try to install it give me error version isn`t supported

Ah, probably because I installed it when my server was running CU20, which is the last supported version. I have installed CU21 since and not had any issues.

Don't know what to do in your case; suggest you create an issue.

**Comment by MoHegazy** [comment]
> > > I've been using the current 3.1.0 release for months without any issues with CU21. Give it a go. Other than that, no idea, this project isn't maintained anymore so it's unlikely.
> > 
> > 
> > then why when i try to install it give me error version isn`t supported
> 
> Ah, probably because I installed it when my server was running CU20, which is the last supported version. I have installed CU21 since and not had any issues.
> 
> Don't know what to do in your case; suggest you create an issue.

ya 
i guess i should create another issue 
or try to upgrade exchange :(

**Comment by mrive2018** [comment]
Hi,
Is there still no compilation for the CU21 version?
If not, can you tell me which files need to be compiled to be added to the previous version in order for it to work?
Thank you

**Comment by mettix** [comment]
> 
> 
> Hi,
> Is there still no compilation for the CU21 version?
> If not, can you tell me which files need to be compiled to be added to the previous version in order for it to work?
> Thank you

You can find the explanation here. Grt
https://github.com/Pro/dkim-exchange/blob/master/CONTRIBUTING.md

**Comment by mrive2018** [comment]
Hi,

<br class="Apple-interchange-newline"><div></div>
78/5000
Is there any way to create an executable to install?
A A simple way.

Thanks

**Comment by Pro** [comment]
Included in #247

**Pull request closed without merging**
