### PR TITLE
3.0.11

### PR DESCRIPTION
**Pull request by PermaGreenCLM**
Fixes # Restore Ex2016 CU1-5.

Changes included in this PR:
- add support: Ex2013 SP1 CU17
- add support: Ex2016 CU6

### CODE REVIEW

**Comment by PermaGreenCLM** [comment]
Please update CHANGELOG.md to 3.0.11 upon merge with master.

**Comment by Ninja101** [comment]
AssemblyVersion/AssemblyFileVersion in Properties/AssemblyInfo.cs needs updating to your version number for it to show correct version in the GUI: https://i.imgur.com/eE8M60r.png

**Comment by geekChamp** [comment]
Perma, sorry for noob question, but how do I download the new bits with the new CU6 release support?

**Comment by CrashTheGreat** [comment]
I join a question. How to receive it?

**Comment by beckzg** [comment]
Me too, how to download?

**Comment by CrashTheGreat** [comment]
Try this link:
https://api.github.com/repos/PermaGreenCLM/dkim-exchange/zipball

**Comment by Ninja101** [comment]
git fetch origin pull/189/head:3.0.11
git checkout 3.0.11

You can do the above to checkout his pull request and compile it

**Pull request closed without merging**
