### PR TITLE
Some improvements and code clean up

### PR DESCRIPTION
**Pull request by semack**
Pro, please check it out and merge to master if agreed. Thanks.

### CODE REVIEW

**Comment by Pro** [comment]
Thanks! Nice work.
Looks good so far. Will test it in the next days and merge it into master.

One small thing for your next commits:
You didn't set up your git username and email correctly. See https://help.github.com/articles/setting-your-email-in-git/ and https://help.github.com/articles/setting-your-username-in-git/

**Comment by semack** [comment]
I've cleaned code of project using Nuget packages and improved Travis build script to use csharp language. Travis-CI build configuration has been added to teh solution. 
All unnecessary files were removed.

**Comment by semack** [comment]
I thought this folder should be appear after Batch Build of the solution. Why do you need to store binaries in source control?

**Comment by Pro** [comment]
As already mentioned, the binaries are used for installing the agent.
In summary, the install process downloads the whole repo as .zip, extracts the files and then installs the apropriate .dll from the corresponding bin folder.
I know that it is bad practice to store binary files within Git but for now that's the easiest solution.
Another way would be to include the binaries on every relase and then download those files instead. If we do it like that than the install process needs to be rewritten

**Comment by semack** [comment]
ok, thx for explanation

**Pull request merged**
