### PR TITLE
Refactor to run as an SmtpRecieveAgent.

### LINKED ISSUE #116: External mails with spoofed email also signed with DKIM
I don't know if this problem related to dkim-exchange, but emails from external server with spoofed sender got also signed.

Goto https://www.wormly.com/test_smtp_server and send sample email with fake sender with own domain name (from fake@mydomain.com to my_valid@mydomain.com). Check signature, it's signed.

Nice way to break in with spam or infected attachments.

### PR DESCRIPTION
**Pull request by jmdevince**
Fixes #116  .

Changes included in this PR:
- Refactor to run as an SmtpRecieveAgent
- TNef messages can be signed just fine when running as an SmtpRecieveAgent
- Cleaned up logic for easier reading
- Implements check to see if the connection is from an external system, will not sign if defined as external system by Exchange. This allows approved relays, internal clients, and cluster members to send mail to be signed.

### CODE REVIEW

**Comment by Pro** [comment]
Nice, thanks!
I'll review the changes and get back to you. Unfortunately github isn't able to show the changes side by side. I've to use another tool for that.

**Comment by jmdevince** [comment]
I do think I have found a bug. It seemed to work initially but now I'm having a problem with multipart messages. I don't know why but for some reason it's not signing the message body correctly so I'm getting Body hash did not verify.

**Comment by jmdevince** [comment]
I may have found the cause which could also be causing #150 ..

http://stackoverflow.com/questions/2699903/unable-to-verify-body-hash-for-dkim

**Comment by Pro** [comment]
If it helps, you can try to Debug into the DKIM Agent:
https://github.com/Pro/dkim-exchange/blob/master/CONTRIBUTING.md#debugging

I used a Virtual Machine for testing

**Comment by Pro** [comment]
Regarding the issue #150 please post your comments directly there to avoid having multiple discussions in this PR (and delete it here)

**Pull request closed without merging**
