### PR TITLE
Version 3.2.0

### PR DESCRIPTION
**Pull request by Ninja101**
Updated version to 3.2.0 to mark Exchange 2019 support.

Changes included in this PR:
- Support for Exchange 2013 CU21 (PR from @davidenco)
- Support for Exchange 2016 CU10 and CU11
- Support for Exchange 2019 Preview & RTM
- Removed Coverity build status from Readme - seems to be defunct
- Targeted .NET Framework 4.7.1 for Exchange 2016 CU10 and newer

Awaiting testing for Exchange 2019, I am not able to deploy it at the moment.

### CODE REVIEW

**Comment by Gumbyohson** [comment]
Has there been any progress getting this merge approved for the official build? Alternately is there any way to install this version manually?

**Comment by ICTSMART** [comment]
While installing this version on Exchange 2019 RTM (15.2.221.12) I've found that on the DKIM Settings tab for some reason Algorithm was set to "RsaSha1" and both Canonicalization options were set to "Relaxed", which seems to be different from the 3.1 version. The created settings.xml file uses <string>Message-ID</string> which seems to be incorrect. Modifying this manually to <string>MessageId</string> fixed the error that showed up in the error log. Anyway, keep up the good work as this is a valuable add-on to many Exchange setups!

**Comment by Ninja101** [comment]
@Pro Are you able to merge?

**Comment by Pro** [comment]
@Ninja101 if you prefer, I can also add you as a maintainer to the project.
Then you can also create new releases?!

**Comment by Pro** [comment]
Thanks for your support!!

**Comment by Pro** [comment]
@Ninja101 I also created a how-to for creating releases:
https://github.com/Pro/dkim-exchange/blob/master/CONTRIBUTING.md#creating-releases

If you agree, then I'll add you as a maintainer and you can create new releases.

Unfortunately I do not have the required time to maintain this repo anymore and would be happy for any help!

**Comment by Ninja101** [comment]
Hey @Pro , Sorry I was away on vacation. Yeah I'll gladly help with maintaining this repo.

Thanks for your help.

**Comment by Pro** [comment]
I added you as a collaborator. You should now be able to create a new release.

If you need support, ping me with my name!

**Comment by Ninja101** [comment]
Thanks, will get this PR released tonight.

**Comment by Ninja101** [comment]
@Pro I have pushed the pre-release out. Everything look okay?

**Comment by Pro** [comment]
Looks good. Lets see if other users can update with the configurator.

**Comment by davidenco** [comment]
Selected the pre-release option and clicked upgrade, after downloading this is what happens:

image

**Comment by davidenco** [comment]
Deleted the temp folder and clicked upgrade again:

image

**Comment by davidenco** [comment]
It seems deleting the /6/ folder breaks everything! Re-creating the /6/ folder, the upgrade button works again, but now getting the same error stating the DLL already exists.

Interestingly, WinRAR says the same after downloading and extracting the ZIP file manually:

image

**Comment by davidenco** [comment]
Last one (sorry!), the CU20 and CU22 folders both contains double the DLLs, except one filename is all lowercase and the other is CamelCase. That'll explain why Windows is freaking out. Can you remove the duplicate DLLs and repackage please?

**Comment by Ninja101** [comment]
Hey, sorry about that - will get on it tonight.

**Comment by Ninja101** [comment]
Sorry about that @davidenco - Have fixed the case issue and re-released 3.2.0

**Comment by davidenco** [comment]
Sorted, all working, thanks. :)

**Pull request merged**
