### PR TITLE
Exchange 2013 SP1 CU21 support

### PR DESCRIPTION
**Pull request by kubik256**
DLL files from Exchange 2013 SP1 CU21 (released in June 2018)

### CODE REVIEW

**Comment by mrive2018** [comment]
Hello,
It does not work for me with the 2013 exchange version cu21. Is there any solution?

**Comment by kubik256** [comment]
It can't work... CU21 is not supported for now. I've just post a pull request to add this CU.
You probably have to read this:
https://github.com/Pro/dkim-exchange/blob/master/README.md
;)

**Comment by mrive2018** [comment]
When can the next update come out?

**Comment by davidenco** [comment]
I have created a new pull request #232 which includes the appropriate files to include the new DLLs.

**Comment by davidenco** [comment]
You need to compile it using Visual Studio. Have a look at the [Compiling](https://github.com/Pro/dkim-exchange/blob/master/CONTRIBUTING.md#compiling) section.

**Comment by mrive2018** [comment]
Hello,
I prefer that the final install version comes out. I prefer not to screw up and do something that is worse.
A greeting.

**Comment by Pro** [comment]
Included in #247

**Pull request closed without merging**
