### PR TITLE
Add support for Exchange 2016 CU13

### PR DESCRIPTION
**Pull request by andrewheberle**
Changes included in this PR:
- Add support for Exchange 2016 CU13
- Adds missing entry for Exchange 2016 CU12 in "coverity.proj"

I am not a Visual Studio guy and don't have the tools/means to ensure this compiles unfortunately, but based on the instructions in CONTRIBUTING I think I have made all the required changes.

### CODE REVIEW

**Comment by sarthurdev** [comment]
Thanks for the PR, merged.

**Comment by noija** [comment]
It's missing the complied binaries in the src directories? Unable to install since the files are missing for Exchange 2016 CU13.

**Comment by sysadm-prs-de** [comment]
Sad but true - unable to install since the files are missing for Exchange 2016 CU13.
Could you please commit the files for 2016 CU13 as well? Thank you so much in advance!

**Comment by slacker220** [comment]
Any chance these will be included soon?  Thanks!

**Comment by sysadm-prs-de** [comment]
We have been able to build for 2016CU3 and already installed it successfully. Can I get write access to the repo to upload the binaries and dll's for this platform? Or shall I simply provide a tarball with the files?

**Comment by sarthurdev** [comment]
If you create a pull request adding the missing libraries I can merge it. If not, I will be able to compile and add them at the weekend.

**Comment by ThomasTrain** [comment]
Also, you need to update the version number, otherwise the update never sees a new version.

**Comment by tedmolin** [comment]
Please could someone compile and upload the files somewhere! @sarthurdev

**Comment by sysadm-prs-de** [comment]
We have already compiled and installed it on one of our servers. I can not upload since I do not have write access to the repo and can not create a pull request. I'd love to help you all, but I do not see how to make progress. Any hints are welcome.

**Comment by sarthurdev** [comment]
Re-relased v3.2.0 with CU13, available as pre-release. Can you verify it? I've tested it in my environment and it works fine.

Will set it as a full release shortly, if all goes well.

**Comment by tedmolin** [comment]
@sarthurdev Thank you! Can confirm it works on my environment.

**Pull request merged**
