### PR TITLE
Add support for Exchange 2019 CU3

### PR DESCRIPTION
**Pull request by DJBenson**
Added support for Exchange 2019 CU3. Build succeeds and installs on my 2019 CU3 environment.

### CODE REVIEW

**Comment by DJBenson** [comment]
I've also built a release package for this but I cannot see how push that back to your repo (sorry I'm fairly new to GitHub).

https://github.com/DJBenson/dkim-exchange/releases/tag/v3.2.2

**Comment by MorleyGit** [comment]
Thanks for making the release package available. Biggest frustration with dkim-exchange
 is the slow release of updates. Unfortunately I do not currently have the skills/tools to compile my own packages.

**Comment by DJBenson** [comment]
> Thanks for making the release package available. Biggest frustration with dkim-exchange
> is the slow release of updates. Unfortunately I do not currently have the skills/tools to compile my own packages.

No problem. I'm a "bleeding-edge" kinda person so I keep my in-house Exchange server up to date so I will release new builds for Ex2019 whenever new CU's are released.

The owner of the original repo has asked for someone to take over and whilst I'm capable of building new releases following his instructions, if the build fails I'm less experienced in C to figure stuff out so not really willing to take it on myself. However I'll keep my repo up to date as best I can.

**Comment by nfmoyt** [comment]
Thank you DJBenson

Just deployed 2019 CU4, Hoping you can help with this as well and a great job sir

**Comment by DJBenson** [comment]
> Thank you DJBenson
> 
> Just deployed 2019 CU4, Hoping you can help with this as well and a great job!

I've built the CU4 binaries but they are untested as I've not updated from CU3 to CU4 yet, I simply ripped the dependencies from the CU4 ISO to be able to build the project.

PR submitted (which I doubt will be merged as my CU3 PR is still outstanding) but my repo is up to date, binaries here:

https://github.com/DJBenson/dkim-exchange/releases/tag/v3.2.3

**Pull request merged**
