### PR TITLE
Add support Exchange 2016 CU5

### PR DESCRIPTION
**Pull request by pcxeon2**
Exchange 2016 CU5

### CODE REVIEW

**Comment by eNNercY1337** [comment]
running the current version of DKIM with CU5 results into crashing the exchange transport service.
would be cool if this could me merged shortly.

**Comment by toto56580** [comment]
+1 !

**Comment by enterdv** [comment]
+1!

**Comment by KosieKramer** [comment]
+1

**Comment by gianfrancocini** [comment]
+1

**Pull request merged**
